In [74]:
from sklearn.neural_network import MLPClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.ensemble import GradientBoostingClassifier

from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report

import pandas as pd
from pathlib import Path

In [75]:
data_dir = Path("../data")
silver_dir = data_dir / "bronze"
training_data = pd.read_csv(silver_dir / "kddcup_data_10_percent.csv")
test_data = pd.read_csv(silver_dir / "corrected.csv")

for col in ['protocol_type', 'service', 'flag']:
    le = LabelEncoder()
    training_data[col] = le.fit_transform(training_data[col])
    test_data[col] = le.fit_transform(test_data[col])

X_train = training_data.drop(columns=["attack_type"])
y_train = training_data["attack_type"]

X_test = test_data.drop(columns=["attack_type"])
y_test = test_data["attack_type"]

training_data.head()

,duration,protocol_type,service,flag,src_bytes,dst_bytes,land,wrong_fragment,urgent,hot,...,dst_host_srv_count,dst_host_same_srv_rate,dst_host_diff_srv_rate,dst_host_same_src_port_rate,dst_host_srv_diff_host_rate,dst_host_serror_rate,dst_host_srv_serror_rate,dst_host_rerror_rate,dst_host_srv_rerror_rate,attack_type
0,0,1,22,9,181,5450,0,0,0,0,...,9,1.0,0.0,0.11,0.0,0.0,0.0,0.0,0.0,normal.
1,0,1,22,9,239,486,0,0,0,0,...,19,1.0,0.0,0.05,0.0,0.0,0.0,0.0,0.0,normal.
2,0,1,22,9,235,1337,0,0,0,0,...,29,1.0,0.0,0.03,0.0,0.0,0.0,0.0,0.0,normal.
3,0,1,22,9,219,1337,0,0,0,0,...,39,1.0,0.0,0.03,0.0,0.0,0.0,0.0,0.0,normal.
4,0,1,22,9,217,2032,0,0,0,0,...,49,1.0,0.0,0.02,0.0,0.0,0.0,0.0,0.0,normal.

In [76]:
test_data.head()

,duration,protocol_type,service,flag,src_bytes,dst_bytes,land,wrong_fragment,urgent,hot,...,dst_host_srv_count,dst_host_same_srv_rate,dst_host_diff_srv_rate,dst_host_same_src_port_rate,dst_host_srv_diff_host_rate,dst_host_serror_rate,dst_host_srv_serror_rate,dst_host_rerror_rate,dst_host_srv_rerror_rate,attack_type
0,0,2,46,9,105,146,0,0,0,0,...,254,1.0,0.01,0.00,0.0,0.0,0.0,0.0,0.0,normal.
1,0,2,46,9,105,146,0,0,0,0,...,254,1.0,0.01,0.00,0.0,0.0,0.0,0.0,0.0,normal.
2,0,2,46,9,105,146,0,0,0,0,...,254,1.0,0.01,0.00,0.0,0.0,0.0,0.0,0.0,normal.
3,0,2,46,9,105,146,0,0,0,0,...,254,1.0,0.01,0.00,0.0,0.0,0.0,0.0,0.0,snmpgetattack.
4,0,2,46,9,105,146,0,0,0,0,...,254,1.0,0.01,0.01,0.0,0.0,0.0,0.0,0.0,snmpgetattack.

In [77]:
mlp_model = MLPClassifier(
    hidden_layer_sizes=(64, 32),
    activation='relu',
    solver='adam',
    max_iter=50,
    batch_size=256,
    random_state=42,
    verbose=True
)

mlp_model.fit(X_train, y_train)
mlp_prediction = mlp_model.predict(X_test)
print(classification_report(y_test, mlp_prediction))

Iteration 1, loss = 0.88065128
Iteration 2, loss = 0.30121892
Iteration 3, loss = 0.27169483
Iteration 4, loss = 0.28058733
Iteration 5, loss = 0.16192925
Iteration 6, loss = 0.12098177
Iteration 7, loss = 0.16349370
Iteration 8, loss = 0.12158343
Iteration 9, loss = 0.11840941
Iteration 10, loss = 0.11330588
Iteration 11, loss = 0.09031451
Iteration 12, loss = 0.09526781
Iteration 13, loss = 0.10122503
Iteration 14, loss = 0.14994430
Iteration 15, loss = 0.12669075
Iteration 16, loss = 0.09627211
Iteration 17, loss = 0.10183112
Iteration 18, loss = 0.12408190
Iteration 19, loss = 0.12559047
Iteration 20, loss = 0.09321104
Iteration 21, loss = 0.08004145
Iteration 22, loss = 0.13758952
Iteration 23, loss = 0.12039445
Iteration 24, loss = 0.10293967
Iteration 25, loss = 0.10761096
Iteration 26, loss = 0.08777131
Iteration 27, loss = 0.09079967
Iteration 28, loss = 0.08685886
Iteration 29, loss = 0.10974946
Iteration 30, loss = 0.11528227
Iteration 31, loss = 0.16636826
Iteration 32, loss = 0.12526020
Training loss did not improve more than tol=0.000100 for 10 consecutive epochs. Stopping.

C:\Users\ryuka\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\Users\ryuka\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\Users\ryuka\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\Users\ryuka\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

                  precision    recall  f1-score   support

        apache2.       0.00      0.00      0.00       794
           back.       1.00      1.00      1.00      1098
buffer_overflow.       0.25      0.05      0.08        22
      ftp_write.       0.00      0.00      0.00         3
   guess_passwd.       0.83      0.00      0.00      4367
     httptunnel.       0.00      0.00      0.00       158
           imap.       0.00      0.00      0.00         1
        ipsweep.       0.80      0.98      0.88       306
           land.       1.00      0.56      0.71         9
     loadmodule.       0.00      0.00      0.00         2
       mailbomb.       0.00      0.00      0.00      5000
          mscan.       0.00      0.00      0.00      1053
       multihop.       0.00      0.00      0.00        18
          named.       0.00      0.00      0.00        17
        neptune.       1.00      1.00      1.00     58001
           nmap.       0.14      1.00      0.24        84
         normal.       0.73      0.98      0.84     60593
           perl.       0.00      0.00      0.00         2
            phf.       0.00      0.00      0.00         2
            pod.       0.46      0.93      0.62        87
      portsweep.       0.71      0.95      0.81       354
   processtable.       0.00      0.00      0.00       759
             ps.       0.00      0.00      0.00        16
        rootkit.       0.00      0.00      0.00        13
          saint.       0.00      0.00      0.00       736
          satan.       0.39      0.99      0.56      1633
       sendmail.       0.00      0.00      0.00        17
          smurf.       1.00      1.00      1.00    164091
  snmpgetattack.       0.00      0.00      0.00      7741
      snmpguess.       0.00      0.00      0.00      2406
      sqlattack.       0.00      0.00      0.00         2
       teardrop.       0.18      0.67      0.28        12
       udpstorm.       0.00      0.00      0.00         2
    warezclient.       0.00      0.00      0.00         0
    warezmaster.       0.00      0.00      0.00      1602
           worm.       0.00      0.00      0.00         2
          xlock.       0.00      0.00      0.00         9
         xsnoop.       0.00      0.00      0.00         4
          xterm.       0.00      0.00      0.00        13

        accuracy                           0.92    311029
       macro avg       0.22      0.26      0.21    311029
    weighted avg       0.88      0.92      0.89    311029

C:\Users\ryuka\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\Users\ryuka\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

In [78]:
dt_model = DecisionTreeClassifier(max_depth = 30, criterion='gini')
dt_model.fit(X_train, y_train)
dt_prediction = dt_model.predict(X_test)
print(classification_report(y_test, dt_prediction))

C:\Users\ryuka\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\Users\ryuka\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\Users\ryuka\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\Users\ryuka\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

                  precision    recall  f1-score   support

        apache2.       0.00      0.00      0.00       794
           back.       0.87      0.98      0.92      1098
buffer_overflow.       0.11      0.05      0.06        22
      ftp_write.       0.00      0.00      0.00         3
   guess_passwd.       1.00      0.00      0.01      4367
     httptunnel.       0.00      0.00      0.00       158
           imap.       0.00      0.00      0.00         1
        ipsweep.       0.71      0.98      0.83       306
           land.       0.47      0.89      0.62         9
     loadmodule.       0.00      0.00      0.00         2
       mailbomb.       0.00      0.00      0.00      5000
          mscan.       0.00      0.00      0.00      1053
       multihop.       0.00      0.00      0.00        18
          named.       0.00      0.00      0.00        17
        neptune.       1.00      0.99      0.99     58001
           nmap.       0.94      0.99      0.97        84
         normal.       0.68      0.99      0.81     60593
           perl.       0.17      0.50      0.25         2
            phf.       1.00      0.50      0.67         2
            pod.       0.83      0.97      0.89        87
      portsweep.       0.33      0.95      0.49       354
   processtable.       0.00      0.00      0.00       759
             ps.       0.00      0.00      0.00        16
        rootkit.       0.00      0.00      0.00        13
          saint.       0.00      0.00      0.00       736
          satan.       0.64      1.00      0.78      1633
       sendmail.       0.00      0.00      0.00        17
          smurf.       1.00      0.96      0.98    164091
  snmpgetattack.       0.00      0.00      0.00      7741
      snmpguess.       0.00      0.00      0.00      2406
      sqlattack.       0.00      0.00      0.00         2
       teardrop.       0.23      1.00      0.38        12
       udpstorm.       0.00      0.00      0.00         2
    warezclient.       0.00      0.00      0.00         0
    warezmaster.       0.99      0.15      0.26      1602
           worm.       0.00      0.00      0.00         2
          xlock.       0.00      0.00      0.00         9
         xsnoop.       0.00      0.00      0.00         4
          xterm.       0.00      0.00      0.00        13

        accuracy                           0.90    311029
       macro avg       0.28      0.30      0.25    311029
    weighted avg       0.87      0.90      0.87    311029

C:\Users\ryuka\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\Users\ryuka\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

In [79]:
rf_model = RandomForestClassifier(
    n_estimators=100,
    random_state=42,
    n_jobs=-1
)
rf_model.fit(X_train, y_train)
rf_prediction = rf_model.predict(X_test)
print(classification_report(y_test, rf_prediction))

C:\Users\ryuka\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\Users\ryuka\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\Users\ryuka\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\Users\ryuka\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

                  precision    recall  f1-score   support

        apache2.       0.00      0.00      0.00       794
           back.       0.79      1.00      0.88      1098
buffer_overflow.       0.40      0.09      0.15        22
      ftp_write.       0.00      0.00      0.00         3
   guess_passwd.       0.00      0.00      0.00      4367
     httptunnel.       0.00      0.00      0.00       158
           imap.       0.00      0.00      0.00         1
        ipsweep.       0.99      0.98      0.99       306
           land.       1.00      0.67      0.80         9
     loadmodule.       0.00      0.00      0.00         2
       mailbomb.       0.00      0.00      0.00      5000
          mscan.       0.00      0.00      0.00      1053
       multihop.       0.00      0.00      0.00        18
          named.       0.00      0.00      0.00        17
        neptune.       1.00      1.00      1.00     58001
           nmap.       0.46      1.00      0.63        84
         normal.       0.72      1.00      0.84     60593
           perl.       0.33      0.50      0.40         2
            phf.       1.00      0.50      0.67         2
            pod.       0.84      0.97      0.90        87
      portsweep.       0.80      0.99      0.88       354
   processtable.       0.00      0.00      0.00       759
             ps.       0.00      0.00      0.00        16
        rootkit.       0.00      0.00      0.00        13
          saint.       0.00      0.00      0.00       736
          satan.       0.67      1.00      0.81      1633
       sendmail.       0.00      0.00      0.00        17
          smurf.       1.00      1.00      1.00    164091
  snmpgetattack.       0.00      0.00      0.00      7741
      snmpguess.       0.00      0.00      0.00      2406
      sqlattack.       0.00      0.00      0.00         2
       teardrop.       0.24      1.00      0.39        12
       udpstorm.       0.00      0.00      0.00         2
    warezclient.       0.00      0.00      0.00         0
    warezmaster.       0.50      0.00      0.00      1602
           worm.       0.00      0.00      0.00         2
          xlock.       0.00      0.00      0.00         9
         xsnoop.       0.00      0.00      0.00         4
          xterm.       0.00      0.00      0.00        13

        accuracy                           0.92    311029
       macro avg       0.28      0.30      0.26    311029
    weighted avg       0.86      0.92      0.89    311029

C:\Users\ryuka\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\Users\ryuka\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

In [80]:
et_model = ExtraTreesClassifier(
    n_estimators=200,
    random_state=42,
    n_jobs=-1,
    max_depth=None
)

et_model.fit(X_train, y_train)
et_prediction = et_model.predict(X_test)
print(classification_report(y_test, et_prediction))

C:\Users\ryuka\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\Users\ryuka\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\Users\ryuka\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\Users\ryuka\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

                  precision    recall  f1-score   support

        apache2.       0.00      0.00      0.00       794
           back.       0.82      1.00      0.90      1098
buffer_overflow.       0.00      0.00      0.00        22
      ftp_write.       0.00      0.00      0.00         3
   guess_passwd.       0.00      0.00      0.00      4367
     httptunnel.       0.00      0.00      0.00       158
           imap.       0.00      0.00      0.00         1
        ipsweep.       0.96      0.98      0.97       306
           land.       1.00      0.78      0.88         9
     loadmodule.       0.00      0.00      0.00         2
       mailbomb.       0.00      0.00      0.00      5000
          mscan.       0.00      0.00      0.00      1053
       multihop.       0.00      0.00      0.00        18
          named.       0.00      0.00      0.00        17
        neptune.       1.00      0.99      0.99     58001
           nmap.       0.47      1.00      0.64        84
         normal.       0.72      1.00      0.84     60593
           perl.       0.17      0.50      0.25         2
            phf.       1.00      0.50      0.67         2
            pod.       0.84      0.97      0.90        87
      portsweep.       0.45      0.99      0.62       354
   processtable.       0.00      0.00      0.00       759
             ps.       0.00      0.00      0.00        16
        rootkit.       0.00      0.00      0.00        13
          saint.       0.00      0.00      0.00       736
          satan.       0.66      1.00      0.79      1633
       sendmail.       0.00      0.00      0.00        17
          smurf.       1.00      1.00      1.00    164091
  snmpgetattack.       0.00      0.00      0.00      7741
      snmpguess.       0.00      0.00      0.00      2406
      sqlattack.       0.00      0.00      0.00         2
       teardrop.       0.24      1.00      0.39        12
       udpstorm.       0.00      0.00      0.00         2
    warezclient.       0.00      0.00      0.00         0
    warezmaster.       0.98      0.07      0.13      1602
           worm.       0.00      0.00      0.00         2
          xlock.       0.00      0.00      0.00         9
         xsnoop.       0.00      0.00      0.00         4
          xterm.       0.00      0.00      0.00        13

        accuracy                           0.92    311029
       macro avg       0.26      0.30      0.26    311029
    weighted avg       0.87      0.92      0.89    311029

C:\Users\ryuka\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\Users\ryuka\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

In [81]:
gb_model = GradientBoostingClassifier(
    n_estimators=50,
    max_depth=3,
    learning_rate=0.1,
    random_state=42
)
gb_model.fit(X_train, y_train)

gb_prediction = gb_model.predict(X_test)
print(classification_report(y_test, gb_prediction))