# Transform
>TODO czemu używamy test data
1. `Corrected data` is just `test data` with corrected labels, so why use test_data file

In [1]:
from pathlib import Path
import pandas as pd

In [2]:
data_dir = Path("../data")
bronze_dir = data_dir / "bronze"
silver_dir = data_dir / "silver"

In [3]:
unlabled_columns = [
    "duration",
    "protocol_type",
    "service",
    "flag",
    "src_bytes",
    "dst_bytes",
    "land",
    "wrong_fragment",
    "urgent",
    "hot",
    "num_failed_logins",
    "logged_in",
    "num_compromised",
    "root_shell",
    "su_attempted",
    "num_root",
    "num_file_creations",
    "num_shells",
    "num_access_files",
    "num_outbound_cmds",
    "is_host_login",
    "is_guest_login",
    "count",
    "srv_count",
    "serror_rate",
    "srv_serror_rate",
    "rerror_rate",
    "srv_rerror_rate",
    "same_srv_rate",
    "diff_srv_rate",
    "srv_diff_host_rate",
    "dst_host_count",
    "dst_host_srv_count",
    "dst_host_same_srv_rate",
    "dst_host_diff_srv_rate",
    "dst_host_same_src_port_rate",
    "dst_host_srv_diff_host_rate",
    "dst_host_serror_rate",
    "dst_host_srv_serror_rate",
    "dst_host_rerror_rate",
    "dst_host_srv_rerror_rate",
]

In [4]:
columns = [*unlabled_columns, "attack_type"]

In [5]:
test_data = pd.read_csv(bronze_dir / "corrected.csv", names=columns)
print(f"Corrected data shape: {test_data.shape}")
test_data.head()

Corrected data shape: (311029, 42)

,duration,protocol_type,service,flag,src_bytes,dst_bytes,land,wrong_fragment,urgent,hot,...,dst_host_srv_count,dst_host_same_srv_rate,dst_host_diff_srv_rate,dst_host_same_src_port_rate,dst_host_srv_diff_host_rate,dst_host_serror_rate,dst_host_srv_serror_rate,dst_host_rerror_rate,dst_host_srv_rerror_rate,attack_type
0,0,udp,private,SF,105,146,0,0,0,0,...,254,1.0,0.01,0.00,0.0,0.0,0.0,0.0,0.0,normal.
1,0,udp,private,SF,105,146,0,0,0,0,...,254,1.0,0.01,0.00,0.0,0.0,0.0,0.0,0.0,normal.
2,0,udp,private,SF,105,146,0,0,0,0,...,254,1.0,0.01,0.00,0.0,0.0,0.0,0.0,0.0,normal.
3,0,udp,private,SF,105,146,0,0,0,0,...,254,1.0,0.01,0.00,0.0,0.0,0.0,0.0,0.0,snmpgetattack.
4,0,udp,private,SF,105,146,0,0,0,0,...,254,1.0,0.01,0.01,0.0,0.0,0.0,0.0,0.0,snmpgetattack.

In [6]:
test_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 311029 entries, 0 to 311028
Data columns (total 42 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   duration                     311029 non-null  int64
 1   protocol_type                311029 non-null  str
 2   service                      311029 non-null  str
 3   flag                         311029 non-null  str
 4   src_bytes                    311029 non-null  int64
 5   dst_bytes                    311029 non-null  int64
 6   land                         311029 non-null  int64
 7   wrong_fragment               311029 non-null  int64
 8   urgent                       311029 non-null  int64
 9   hot                          311029 non-null  int64
 10  num_failed_logins            311029 non-null  int64
 11  logged_in                    311029 non-null  int64
 12  num_compromised              311029 non-null  int64
 13  root_shell                   311029 non-null  int64
 14  su_attempted                 311029 non-null  int64
 15  num_root                     311029 non-null  int64
 16  num_file_creations           311029 non-null  int64
 17  num_shells                   311029 non-null  int64
 18  num_access_files             311029 non-null  int64
 19  num_outbound_cmds            311029 non-null  int64
 20  is_host_login                311029 non-null  int64
 21  is_guest_login               311029 non-null  int64
 22  count                        311029 non-null  int64
 23  srv_count                    311029 non-null  int64
 24  serror_rate                  311029 non-null  float64
 25  srv_serror_rate              311029 non-null  float64
 26  rerror_rate                  311029 non-null  float64
 27  srv_rerror_rate              311029 non-null  float64
 28  same_srv_rate                311029 non-null  float64
 29  diff_srv_rate                311029 non-null  float64
 30  srv_diff_host_rate           311029 non-null  float64
 31  dst_host_count               311029 non-null  int64
 32  dst_host_srv_count           311029 non-null  int64
 33  dst_host_same_srv_rate       311029 non-null  float64
 34  dst_host_diff_srv_rate       311029 non-null  float64
 35  dst_host_same_src_port_rate  311029 non-null  float64
 36  dst_host_srv_diff_host_rate  311029 non-null  float64
 37  dst_host_serror_rate         311029 non-null  float64
 38  dst_host_srv_serror_rate     311029 non-null  float64
 39  dst_host_rerror_rate         311029 non-null  float64
 40  dst_host_srv_rerror_rate     311029 non-null  float64
 41  attack_type                  311029 non-null  str
dtypes: float64(15), int64(23), str(4)
memory usage: 99.7 MB

In [7]:
train_data = pd.read_csv(bronze_dir / "kddcup_data_10_percent.csv", names=columns)
print(f"Training data shape: {train_data.shape}")
train_data.head()

Training data shape: (494021, 42)

,duration,protocol_type,service,flag,src_bytes,dst_bytes,land,wrong_fragment,urgent,hot,...,dst_host_srv_count,dst_host_same_srv_rate,dst_host_diff_srv_rate,dst_host_same_src_port_rate,dst_host_srv_diff_host_rate,dst_host_serror_rate,dst_host_srv_serror_rate,dst_host_rerror_rate,dst_host_srv_rerror_rate,attack_type
0,0,tcp,http,SF,181,5450,0,0,0,0,...,9,1.0,0.0,0.11,0.0,0.0,0.0,0.0,0.0,normal.
1,0,tcp,http,SF,239,486,0,0,0,0,...,19,1.0,0.0,0.05,0.0,0.0,0.0,0.0,0.0,normal.
2,0,tcp,http,SF,235,1337,0,0,0,0,...,29,1.0,0.0,0.03,0.0,0.0,0.0,0.0,0.0,normal.
3,0,tcp,http,SF,219,1337,0,0,0,0,...,39,1.0,0.0,0.03,0.0,0.0,0.0,0.0,0.0,normal.
4,0,tcp,http,SF,217,2032,0,0,0,0,...,49,1.0,0.0,0.02,0.0,0.0,0.0,0.0,0.0,normal.

In [8]:
train_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 494021 entries, 0 to 494020
Data columns (total 42 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   duration                     494021 non-null  int64
 1   protocol_type                494021 non-null  str
 2   service                      494021 non-null  str
 3   flag                         494021 non-null  str
 4   src_bytes                    494021 non-null  int64
 5   dst_bytes                    494021 non-null  int64
 6   land                         494021 non-null  int64
 7   wrong_fragment               494021 non-null  int64
 8   urgent                       494021 non-null  int64
 9   hot                          494021 non-null  int64
 10  num_failed_logins            494021 non-null  int64
 11  logged_in                    494021 non-null  int64
 12  num_compromised              494021 non-null  int64
 13  root_shell                   494021 non-null  int64
 14  su_attempted                 494021 non-null  int64
 15  num_root                     494021 non-null  int64
 16  num_file_creations           494021 non-null  int64
 17  num_shells                   494021 non-null  int64
 18  num_access_files             494021 non-null  int64
 19  num_outbound_cmds            494021 non-null  int64
 20  is_host_login                494021 non-null  int64
 21  is_guest_login               494021 non-null  int64
 22  count                        494021 non-null  int64
 23  srv_count                    494021 non-null  int64
 24  serror_rate                  494021 non-null  float64
 25  srv_serror_rate              494021 non-null  float64
 26  rerror_rate                  494021 non-null  float64
 27  srv_rerror_rate              494021 non-null  float64
 28  same_srv_rate                494021 non-null  float64
 29  diff_srv_rate                494021 non-null  float64
 30  srv_diff_host_rate           494021 non-null  float64
 31  dst_host_count               494021 non-null  int64
 32  dst_host_srv_count           494021 non-null  int64
 33  dst_host_same_srv_rate       494021 non-null  float64
 34  dst_host_diff_srv_rate       494021 non-null  float64
 35  dst_host_same_src_port_rate  494021 non-null  float64
 36  dst_host_srv_diff_host_rate  494021 non-null  float64
 37  dst_host_serror_rate         494021 non-null  float64
 38  dst_host_srv_serror_rate     494021 non-null  float64
 39  dst_host_rerror_rate         494021 non-null  float64
 40  dst_host_srv_rerror_rate     494021 non-null  float64
 41  attack_type                  494021 non-null  str
dtypes: float64(15), int64(23), str(4)
memory usage: 158.3 MB

In [9]:
unlabeled_test_data = pd.read_csv(bronze_dir / "kddcup_testdata_unlabeled_10_percent.csv", names=unlabled_columns)

In [10]:
unlabeled_test_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 311029 entries, 0 to 311028
Data columns (total 41 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   duration                     311029 non-null  int64
 1   protocol_type                311029 non-null  str
 2   service                      311029 non-null  str
 3   flag                         311029 non-null  str
 4   src_bytes                    311029 non-null  int64
 5   dst_bytes                    311029 non-null  int64
 6   land                         311029 non-null  int64
 7   wrong_fragment               311029 non-null  int64
 8   urgent                       311029 non-null  int64
 9   hot                          311029 non-null  int64
 10  num_failed_logins            311029 non-null  int64
 11  logged_in                    311029 non-null  int64
 12  num_compromised              311029 non-null  int64
 13  root_shell                   311029 non-null  int64
 14  su_attempted                 311029 non-null  int64
 15  num_root                     311029 non-null  int64
 16  num_file_creations           311029 non-null  int64
 17  num_shells                   311029 non-null  int64
 18  num_access_files             311029 non-null  int64
 19  num_outbound_cmds            311029 non-null  int64
 20  is_host_login                311029 non-null  int64
 21  is_guest_login               311029 non-null  int64
 22  count                        311029 non-null  int64
 23  srv_count                    311029 non-null  int64
 24  serror_rate                  311029 non-null  float64
 25  srv_serror_rate              311029 non-null  float64
 26  rerror_rate                  311029 non-null  float64
 27  srv_rerror_rate              311029 non-null  float64
 28  same_srv_rate                311029 non-null  float64
 29  diff_srv_rate                311029 non-null  float64
 30  srv_diff_host_rate           311029 non-null  float64
 31  dst_host_count               311029 non-null  int64
 32  dst_host_srv_count           311029 non-null  int64
 33  dst_host_same_srv_rate       311029 non-null  float64
 34  dst_host_diff_srv_rate       311029 non-null  float64
 35  dst_host_same_src_port_rate  311029 non-null  float64
 36  dst_host_srv_diff_host_rate  311029 non-null  float64
 37  dst_host_serror_rate         311029 non-null  float64
 38  dst_host_srv_serror_rate     311029 non-null  float64
 39  dst_host_rerror_rate         311029 non-null  float64
 40  dst_host_srv_rerror_rate     311029 non-null  float64
dtypes: float64(15), int64(23), str(3)
memory usage: 97.3 MB

In [11]:
silver_dir.mkdir(parents=True, exist_ok=True)


train_data.to_csv(silver_dir / "train_data.csv", index=False,)
test_data.to_csv(silver_dir / "test_data.csv", index=False)
unlabeled_test_data.to_csv(silver_dir / "unlabled_test_data.csv", index=False)